# Generated by Django 4.1.1 on 2022-09-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='original_file')),
                ('video_240', models.FileField(blank=True, null=True, upload_to='original_file')),
                ('video_360', models.FileField(blank=True, null=True, upload_to='original_file')),
                ('convert_time', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
